### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [Foucauld/UrbanTag#1]
Hi.
I am a developer of "OpenCVForUnity".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "OpenCVForUnity" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by Foucauld** [comment]
I'll remove it, 
Sorry for this.
